### ISSUE TITLE
Automatically announce newly scheduled meetups

### ISSUE THREAD

**Issue by zoni** [Djiit/err-meetup#1]
It would be cool if I could configure this plugin to watch/track a selected meetup groups and have the bot automatically send an announcement into chat when those groups schedule new meetup dates.

In other words; Say I tell it to track the [Amsterdam Python Meetup Group](http://www.meetup.com/Amsterdam-Python-Meetup-Group/) (APMG), it would be cool if it would send a chat announcement (into a room of my choice) whenever the APMG has a new meetup.

**Comment by Djiit** [comment]
PR #2 add a basic watchlist management feature. Would you prefer to configure the targeted chatrooms in `config.py` or through chat messages (i.e. `!plugin config meetup {'CHATROOMS': ['#broadcasts']}`) ?

**Comment by zoni** [comment]
Configuration through `!plugin config` has my strong preference (but then I'm also talking as a maintainer of errbot itself). Our vision is to have all plugin configuration through `!plugin config`, never by editing `config.py`.

(We are thinking about making it possible to access the `!plugin config` stuff from outside errbot for those people who want to pre-configure things from, say, a configuration management system though: https://github.com/errbotio/errbot/issues/608)
